Repository EveryAnalytics-Study/todo-list, pull requests merged in 2021-09, with the labels that each got.

#17 Feat: TodoContext 제작
  src/contexts/todoContext.tsx
  src/pages/Board.tsx
  src/types/Todo.ts
Labels: ✨new feature

#24 Fix/seperate todolist
  src/components/TodoItem.tsx
  src/components/TodoList.tsx
  src/pages/Board.tsx
Labels: ⚒refactor

#22 Feat: 디자인 수정
  rollup.config.js
  src/App.tsx
  src/components/Header.tsx
  src/components/TodoItem.tsx
  src/components/TodosFooter.tsx
  src/components/TodosHeader.tsx
  src/pages/Board.tsx
Labels: enhancement
